// webclientv3/src/app/shared/loading-indicator/loading-indicator.component.ts
import { Component, OnInit } from "@angular/core";
import { LoadingIndicator } from "./loading-indicator.service";

@Component({
  selector: "ec-loading-indicator",
  styles: [
    `
    mat-progress-bar{
        position: fixed;
        z-index: 30001;
        top: 0px;
    }
  `
  ],
  template: `

    <mat-progress-bar color="warn" mode="indeterminate" class="loader" *ngIf="loadingIndicator.isVisible()">
    </mat-progress-bar>
  `
})
export class LoadingIndicatorComponent implements OnInit {
  constructor(public loadingIndicator: LoadingIndicator) {}

  ngOnInit() {}
}

// webclientv4/src/app/loading/LoadingIndicator.vue
<template>
  <ProgressBar
    v-if="loadingStore.isLoading"
    mode="indeterminate"
    data-testid="progress-bar"
    class="loading-indicator"
  />
</template>

<script setup lang="ts">
import ProgressBar from 'primevue/progressbar';
import { useLoadingIndicatorStore } from './loadingIndicatorStore';

const loadingStore = useLoadingIndicatorStore();
</script>

<style scoped>
.loading-indicator {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  z-index: 9999;
  height: 4px;
}
</style>
