// webclientv3/src/app/transactions/transaction-summary/transaction-summary.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { BankAccountData } from "../../bank-accounts/bank-account.model";
import {SettingsService} from "../../shared/settings.service";
import {total} from "../../util/total";
import { AllocationData } from "../allocation-data.model";
import { TransactionData } from "../transaction-data.model";

@Component({
  selector: "ec-transaction-summary",
  styles: [`
    .heading {
      flex: 2 0 auto;
      font-weight: bold;
    }
    .value {
      flex: 1 0 auto;
      text-align: right;
    }
    .total {
      font-size: 16px;
      border-top: 1px solid black;
    }
  `],
  template: `
    <mat-card>
      <mat-card-content>
        <div fxLayout="row">
          <span class="heading">Last Bank Balance</span>
          <span class="value">{{ lastBankBalance() | ecMoney }}</span>
        </div>

        <div fxLayout="row">
          <span class="heading">Transaction Total</span>
          <span class="value">{{ transactionTotal() | ecMoney }}</span>
        </div>

        <div fxLayout="row" class="total">
          <span class="heading">Current Bank Balance</span>
          <span class="value">
            <ec-money-field [value]="currentBankBalance()" [highlightPositive]="true"></ec-money-field>
          </span>
        </div>

        <ng-container *ngIf="showBudgetBalance()">
          <div fxLayout="row">
            <span class="heading">Current Budget Balance</span>
            <span class="value">{{ lastBudgetBalance() | ecMoney }}</span>
          </div>

          <div fxLayout="row" class="total">
            <span class="heading">Difference (Bank vs Budget)</span>
            <span class="value">
                <ec-money-field [value]="budgetDifference()" [highlightPositive]="true"></ec-money-field>
            </span>
          </div>
        </ng-container>

        <ng-container *ngIf="showUnpaidBalance()">
          <div fxLayout="row">
            <span class="heading">Unpaid Balance</span>
            <span class="value">
              <ec-money-field [value]="unpaidBalance()" [highlightPositive]="true"></ec-money-field>
            </span>
          </div>
          <div fxLayout="row">
            <span class="heading">Unpaid Difference</span>
            <span class="value">
              <ec-money-field [value]="unpaidDifference()" [highlightPositive]="true"></ec-money-field>
            </span>
          </div>
        </ng-container>
      </mat-card-content>
    </mat-card>
  `
})
export class TransactionSummaryComponent implements OnInit {
  primary_budget_account_id: number;

  @Input() bankAccount: BankAccountData;
  @Input() transactions: TransactionData[];
  @Input() allocations: AllocationData[];

  constructor(
    private settingsService: SettingsService
  ) {}

  ngOnInit() {
    this.settingsService.getSettings().subscribe(settings => {
      this.primary_budget_account_id = settings.primary_budget_account_id;
    });
  }

  lastBankBalance() {
    if (!this.bankAccount) {
      return 0;
    }
    return this.bankAccount.closing_balance;
  }

  transactionTotal() {
    if (!this.transactions) {
      return 0;
    }

    let totalWithdrawals = 0;
    let totalDeposits = 0;

    this.transactions.forEach(transaction => {
      if (!transaction.deleted) {
        totalWithdrawals += transaction.withdrawal_amount;
        totalDeposits += transaction.deposit_amount;
      }
    });

    return totalDeposits - totalWithdrawals;
  }

  currentBankBalance() {
    return this.lastBankBalance() + this.transactionTotal();
  }

  showBudgetBalance() {
    if (!this.bankAccount) {
      return false;
    }
    return this.bankAccount.id === this.primary_budget_account_id;
  }

  lastBudgetBalance() {
    return (
      total(this.allocations, "amount") -
      total(this.allocations, "spent")
    );
  }

  currentBudgetBalance() {
    return this.lastBudgetBalance();
  }

  budgetDifference() {
    return this.currentBankBalance() - this.currentBudgetBalance();
  }

  showUnpaidBalance() {
    if (!this.bankAccount) {
      return false;
    }

    return this.bankAccount.account_type === "credit_card";
  }

  unpaidBalance() {
    if (!this.transactions) {
      return 0;
    }

    let unpaidTransactions = this.transactions.filter(transaction => {
      return !transaction.paid;
    });

    return total(unpaidTransactions, "net_amount");
  }

  unpaidDifference() {
    return this.currentBankBalance() - this.unpaidBalance();
  }
}

// webclientv4/src/app/transactions/TransactionSummary.vue
<template>
  <div class="transaction-summary">
    <div class="summary-row">
      <span class="summary-label">Last Bank Balance</span>
      <span class="summary-value" data-testid="last-bank-balance">{{ centsToDollars(lastBankBalance) }}</span>
    </div>

    <div class="summary-row">
      <span class="summary-label">Transaction Total</span>
      <span class="summary-value" data-testid="transaction-total">{{ centsToDollars(transactionTotal) }}</span>
    </div>

    <div class="summary-row summary-row--total">
      <span class="summary-label">Current Bank Balance</span>
      <span
        class="summary-value"
        data-testid="current-bank-balance"
        :class="{ positive: currentBankBalance > 0, negative: currentBankBalance < 0 }"
      >{{ centsToDollars(currentBankBalance) }}</span>
    </div>

    <template v-if="showBudgetBalance">
      <div class="summary-row" data-testid="budget-balance-section">
        <span class="summary-label">Current Budget Balance</span>
        <span class="summary-value" data-testid="current-budget-balance">{{ centsToDollars(currentBudgetBalance) }}</span>
      </div>

      <div class="summary-row summary-row--total">
        <span class="summary-label">Difference (Bank vs Budget)</span>
        <span
          class="summary-value"
          data-testid="budget-difference"
          :class="{ positive: budgetDifference > 0, negative: budgetDifference < 0 }"
        >{{ centsToDollars(budgetDifference) }}</span>
      </div>
    </template>

    <template v-if="showUnpaidBalance">
      <div class="summary-row" data-testid="unpaid-balance-section">
        <span class="summary-label">Unpaid Balance</span>
        <span
          class="summary-value"
          data-testid="unpaid-balance"
          :class="{ positive: unpaidBalance > 0, negative: unpaidBalance < 0 }"
        >{{ centsToDollars(unpaidBalance) }}</span>
      </div>

      <div class="summary-row">
        <span class="summary-label">Unpaid Difference</span>
        <span
          class="summary-value"
          data-testid="unpaid-difference"
          :class="{ positive: unpaidDifference > 0, negative: unpaidDifference < 0 }"
        >{{ centsToDollars(unpaidDifference) }}</span>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useSettingsStore } from '../settings/settingsStore';
import { centsToDollars } from '../shared/util/cents-to-dollars';
import { total } from '../shared/util/total';
import type { TransactionData, AllocationData } from './transaction.types';
import type { BankAccountData } from '../bank-accounts/bankAccount.types';

const props = defineProps<{
  bankAccount?: BankAccountData;
  transactions: TransactionData[];
  allocations: AllocationData[];
}>();

const settingsStore = useSettingsStore();

const lastBankBalance = computed(() => props.bankAccount?.closing_balance ?? 0);

const transactionTotal = computed(() => {
  if (!props.transactions.length) return 0;
  let totalWithdrawals = 0;
  let totalDeposits = 0;
  for (const t of props.transactions) {
    if (!t.deleted) {
      totalWithdrawals += t.withdrawal_amount ?? 0;
      totalDeposits += t.deposit_amount ?? 0;
    }
  }
  return totalDeposits - totalWithdrawals;
});

const currentBankBalance = computed(() => lastBankBalance.value + transactionTotal.value);

const showBudgetBalance = computed(() => {
  if (!props.bankAccount) return false;
  return props.bankAccount.id === settingsStore.settings.primary_budget_account_id;
});

const currentBudgetBalance = computed(() => {
  return total(props.allocations, 'amount') - total(props.allocations, 'spent');
});

const budgetDifference = computed(() => currentBankBalance.value - currentBudgetBalance.value);

const showUnpaidBalance = computed(() => {
  if (!props.bankAccount) return false;
  return props.bankAccount.account_type === 'credit_card' || props.bankAccount.is_credit_card === true;
});

const unpaidBalance = computed(() => {
  const unpaid = props.transactions.filter((t) => t.status !== 'paid' && !t.deleted);
  return total(unpaid, 'net_amount');
});

const unpaidDifference = computed(() => currentBankBalance.value - unpaidBalance.value);
</script>

<style scoped>
.transaction-summary {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  padding: 1rem;
  border: 1px solid var(--p-surface-200);
  border-radius: 6px;
}

.summary-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.2rem 0;
}

.summary-row--total {
  border-top: 1px solid var(--p-surface-300);
  margin-top: 0.25rem;
  padding-top: 0.4rem;
  font-size: 1rem;
}

.summary-label {
  font-weight: 500;
  flex: 2;
}

.summary-value {
  flex: 1;
  text-align: right;
}

.positive {
  color: var(--p-green-600);
}

.negative {
  color: var(--p-red-600);
}
</style>
